import nbconvert

# Set up the converter
exporter = nbconvert.MarkdownExporter()

# Convert the notebook to markdown
with open('main.ipynb') as f:
    notebook_content = f.read()

# Export the notebook content
(body, resources) = exporter.from_notebook_node(nbconvert.reads(notebook_content, as_version=4))

# Save the markdown file
with open('output.md', 'w') as f:
    f.write(body)

# Optionally: Save images generated by the notebook to a folder
for image_name, image_data in resources.get('outputs', {}).items():
    with open(f'output_files/{image_name}', 'wb') as img_file:
        img_file.write(image_data)
